linux-system-roles/mssql

- .github/workflows/tox.yml
- molecule/default/molecule.yml
Upgrade to tox-lsr 2.2.0 to pick up fix for improving collection
testing to get rid of black.
> use tox-lsr 2.2.0

- tests/tasks/verify_settings.yml
Fixing badly written (by myself) code
> Use variables instead of plain-text package names in tests verification

- tests/ansible.cfg
The CI tests take 5h total because each test downloads the mssql packages again each time.
> Print the time that task in the CI tests last

- tests/tests_powershell.yml
Fedora VMs do not have enough disk space to install Powershell on top of
the packages installed in the tests_idempotency playbook, hence moving
the install to a separate test for now. Later, when we will use BaseOS
CI, we will be able to increase the disk size of Fedora VMs.
> Move PowerShell install to a separate test

- tests/tests_tls.yml
The role uses openssl to generate TLS certificate and key.
Previously, OpenSSL was a dependency of pcs. That is no longer the case
since pcs-0.10.8-2.
Hence, the tls tests fail on Fedora because openssl is missing.
> Install openssl on the control node

- tasks/main.yml
Remove the block-rescue structure so that Ansible does not print errors
Fixes #24
> Avoid failing the tuned tasks

- tasks/main.yml
- tests/tasks/check_header.yml
- tests/tests_accept_eula_2019.yml
- tests/tests_default_2019.yml
- tests/tests_idempotency_2017.yml
- tests/tests_idempotency_2019.yml
- tests/tests_input_sql_file_2019.yml
- tests/tests_password_2017.yml
- tests/tests_password_2019.yml
- tests/tests_powershell_2019.yml
- tests/tests_tls_2019.yml
- tests/tests_upgrade_2017.yml
Some sqlcmd commands remove the header from config. E.g.
/opt/mssql/bin/mssql-conf set sqlagent.enabled "True"
Inserting the header must be executed at the end of the role
https://bugzilla.redhat.com/show_bug.cgi?id=2057651
> Move inserting ansible_managed header at the end of the tasks

- tasks/main.yml
- tasks/set_vars.yml
- tests/ansible.cfg
- tests/setup-snapshot.yml
- tests/tasks/snapshot_install_packages.yml
- tests/tests_accept_eula_2019.yml
- tests/tests_default_2019.yml
- tests/tests_idempotency_2017.yml
- tests/tests_idempotency_2019.yml
- tests/tests_input_sql_file_2019.yml
- tests/tests_powershell_2019.yml
- vars/main.yml
Some users use gather_facts: false in their playbooks. This changes
the role to work in that case, by gathering only the facts it requires
to run.
CI testing can be sped up by creating a snapshot image pre-installed
with packages. tests/setup-snapshot.yml can be used by a CI system
to do this.
> support gather_facts: false; support setup-snapshot.yml

- README.md
- defaults/main.yml
- tasks/main.yml
- tests/tasks/check_header.yml
- tests/templates/get_ansible_managed.j2
- tests/tests_tls_2019.yml
SQL Server role should be able to use TLS cert and key files that are
already on managed nodes
> Add mssql_tls_remote_src

- .collection/README.md
- README.md
- defaults/main.yml
- tasks/input_sql_file.yml
- tasks/main.yml
- tasks/mssql_conf_setting.yml
- tests/tasks/verify_package.yml
- tests/tasks/verify_settings.yml
- vars/main.yml
This should help to reduce the size of #62
> Refractor for ha

- README.md
- defaults/main.yml
- tasks/main.yml
- tests/sql_script.sql
- tests/tests_configure_ha_cluster.yml
- tests/tests_input_sql_file_2019.yml
Previously, `mssql_input_sql_file` input SQL files at the end of the
role invocation. However, users must input some SQL files at the
beginning of the role before it applies any configuration to SQL Server.
`mssql_pre_input_sql_file` and `mssql_post_input_sql_file` has been
added to address this functionality.
> Replace simple `mssql_input_sql_file` with `pre` and `post` variables

- .github/workflows/changelog_to_tag.yml
Removing Github Action that publishes a collection in a legacy role format to Galaxy. mssql only publishes microsoft.sql collection to Galaxy, so this is not applicable.
> Do not publish legacy role format to galaxy, mssql only has a collection

- tasks/main.yml
- templates/configure_ag.j2
Sort primary replica as the last in the list
Sort witness replica as the next-to-last in the list
Configure primary last because it has information about other replicas
Configure witness next-to-last to ensure that previous witness replica is
removed beforehand. Otherwise, script fails with 'only supports one replica
> Sort ansible_play_hosts to ensure configure_ag script runs smoothly

- tasks/input_sql_file.yml
- tasks/main.yml
Previously, the role would use a workaround of setting a
__mssql_primary_successful variable to define whether the primary node
really failed or not. This was required because any_errors_fatal: true
would not work when run in a block where rescue or always block would
execute.
This workaround creates troubles when the order of hosts in inventory is
not primary-secondary-witness - the role skips a rescue block after
failing tasks in the block on primary and goes to the next block.
Removing the workardound for stability. Certificate and private key now
won't be removed from the control node in the case of failure, but those
files will be removed on a next successful role invocation.
> Remove the workaround for `any_errors_fatal: true`

- tasks/input_sql_file.yml
This is required because in the case when a task that precedes the
inputtask fails, the print task prints a previous result
> Unset the __mssql_sqlcmd_input_file variable

- CHANGELOG.md
[1.2.1] - 2022-08-23
- Use firewall role to configure firewall for SQL Server (#77)
- Add `mssql_firewall_configure` that controls whether to manage firewall ports.
- If set to `true`, the role opens the TCP port provided with `mssql_tcp_port`
and if applicable closes the previously opened port.
- Replace simple `mssql_input_sql_file` with `pre` and `post` variables (#84)
- Previously, `mssql_input_sql_file` input SQL files at the end of the
role invocation. However, users must input some SQL files at the
beginning of the role before it applies any configuration to SQL Server.
`mssql_pre_input_sql_file` and `mssql_post_input_sql_file` has been
added to address this functionality.
- Replace agents in cluster configuration with watchdog (#83)
- Change bare-metal HA …
> Version 1.2.1 - CHANGELOG.md [citest skip]

- README.md
- defaults/main.yml
- tasks/main.yml
- templates/replicate_db.j2
- tests/tests_configure_ha_cluster.yml
- Replace mssql_ha_db_name with mssql_ha_db_names so that users can
provide a list of databases to be replicated
- Previously, a database must exist in SQL Server to create a cluster.
Now mssql_ha_db_names is optional, if it is not provided the role
creates a cluster without replicating databases
- Remove mssql_ha_db_backup_path and always back up to the
/var/opt/mssql/data/ directory for simplicity
> Add mssql_ha_db_names to let users replicate multiple DBs

- README.md
- defaults/main.yml
- tasks/main.yml
- tests/tests_configure_ha_cluster.yml
- tests/tests_tcp_firewall.yml
Previously, two variables existed, mssql_ha_firewall_configure and
mssql_firewall_configure. For simplicity, the role now only uses
mssql_firewall_configure for configuring firewall.
mssql_manage_firewall makes more sense because firewall is a service and
the word manage fits it better.
Other system roles use the rolename_manage_firewall wording too and
mssql must be consistent with them for simplicity
> Remove mssql_ha_firewall_configure, rename mssql_firewall_configure to mssql_manage_firewall

- CHANGELOG.md
[1.2.2] - 2022-08-25
- Add mssql_ha_db_names to let users replicate multiple DBs
- Replace mssql_ha_db_name with mssql_ha_db_names so that users can
provide a list of databases to be replicated
- Previously, a database must exist in SQL Server to create a cluster.
Now mssql_ha_db_names is optional, if it is not provided the role
creates a cluster without replicating databases
- Remove mssql_ha_db_backup_path and always back up to the
/var/opt/mssql/data/ directory for simplicity
- Remove `mssql_ha_firewall_configure`, rename `mssql_firewall_configure` to `mssql_manage_firewall` (#104)
- Previously, two variables existed, `mssql_ha_firewall_configure` and
`mssql_firewall_configure`. For simplicity, the role now only uses
`mssql_firewall_configure` for configuring …
> Version 1.2.2 - CHANGELOG.md [citest skip]

- README.md
- templates/replicate_db.j2
This change fixes the bug where only the first database provided with
mssql_ha_db_names got replicated
> Replicate all provided databases

- CHANGELOG.md
[1.2.4] - 2022-09-01
- none
- Replicate all provided databases (#110)
- This change fixes the bug where only the first database provided with
mssql_ha_db_names got replicated
- Clarify that the role does not remove not listed databases
- Input multiple sql scripts (#109)
- Allow _input_sql_file vars to accept list of files
- Flush handlers prior to inputting post sql script
- Note that ha_cluster is not idempotent (#111)
- none
> Version 1.2.4 - CHANGELOG.md [citest skip]

- meta/main.yml
mssql-server package does not support Fedora at all but it works on Fedora <36. Once Microsoft adds mssql-server package for RHEL 9 it should work on Fedora 36 too.
> Remove support for Fedora 36

- README.md
With more configuration scenarios added, README file became messy. These changes split README file into sections, each describing a specific user story and providing example playbooks in-place.
> Restructure README files to split it into available scenarios

- .collection/README.md
- .collection/galaxy.yml
- .github/actions/custom-woke-action/LICENSE
- .github/actions/custom-woke-action/README.md
- .github/actions/custom-woke-action/action.yml
- .github/actions/custom-woke-action/entrypoint.sh
- .github/actions/custom-woke-action/testdata/bad.txt
- .github/workflows/woke.yml
- CHANGELOG.md
**Add check for non-inclusive language.**
Add a check for usage of terms and language that is considered
non-inclusive. We are using the woke tool for this with a wordlist
that can be found at
https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/config_files/woke.yml
Note: this commit uses the customized woke placed locally in .github/actions/custom-woke-action to support a new option --count-only-error-for-failure option.
The local action custom-woke-action will be replaced with the official woke once https://github.com/get-woke/woke/pull/252 (Add an option "--count-only-error-for-failure") is processed.
**Clean up non-inclusive words.** 
- .collection/README.md
- .collection/galaxy.yml
- CHANGELOG.md
Note: the changes in .collection/README.md and .collection/galaxy.yml …
> Add check for non-inclusive language

- README.md
- defaults/main.yml
- tasks/main.yml
- templates/configure_ag.j2
- templates/configure_endpoint.j2
- tests/templates/configure_ag_cluster_type_none.j2
- tests/tests_configure_ha_cluster.yml
As per feedback from Microsoft, mssql_ha_listener_port should be called HA communication port (or HA_log_transport_port),  as that port is used for the transaction log replication between primary and secondary replica. Listener is a term used for AG listener associated with AG which is used to route client connection to primary replica (or read only secondary replica based on configuration and request type).
> Rename mssql_ha_listener_port to mssql_ha_log_transport_port

- CHANGELOG.md
[1.3.0] - 2023-01-31
- Rename mssql_ha_listener_port to mssql_ha_endpoint_port (#166) As per feedback from Microsoft, mssql_ha_listener_port should be called mssql_ha_endpoint_port, as that port is used when creating endpoint for replication between primary and secondary replica. Listener is a term used for AG listener associated with AG which is used to route client connection to primary replica (or read only secondary replica based on configuration and request type). And listener uses tcp_port, hence the confusion.
- Restructure README files to split it into available scenarios (#161)
- Add AD integration functionality (#159)
- Add mssql version to set up
- Add clean up for realm to clean_up_mssql.yml
- Remove setting passwords with environment: Set password inline …
> Version 1.3.0 - append to CHANGELOG.md [citest skip]

- templates/get_ansible_managed.j2
- tests/templates/get_ansible_managed.j2
Add role name to the generated config files.
```
```
Note: This information is provided to help customers identify that it was generated by System Roles. It may also be used for future analysis.
> [WIP] Fingerprint RHEL System Role managed config files

- .github/workflows/ansible-managed-var-comment.yml
- .github/workflows/ansible-plugin-scan.yml
- .github/workflows/ansible-test.yml
- contributing.md
The major version bump is because tox-lsr 3 drops support
for tox version 2.  If you are using tox 2 you will need to
upgrade to tox 3 or 4.
tox-lsr 3.0.0 adds support for tox 4, commitlint, and ansible-lint-collection
See https://github.com/linux-system-roles/tox-lsr/releases/tag/3.0.0
for full release notes
> ci: update tox-lsr to version 3.0.0

- README.md
- defaults/main.yml
- tasks/configure_storage_paths.yml
- tasks/main.yml
- tests/tasks/mssql_conf_verify.yml
- tests/tasks/verify_settings.yml
- tests/tests_idempotency_2017.yml
- tests/tests_idempotency_2019.yml
- tests/tests_idempotency_2022.yml
Previously, the role was configuring the default data and logs storage
paths. Currently, you can provide custom storage paths with variables
`mssql_datadir` and `mssql_logdir`, and optionally set permissions for
the custom paths with `mssql_datadir_mode` and `mssql_logdir_mode`
variables.
> feat: Support custom data and logs storage paths

- README.md
- defaults/main.yml
- tasks/main.yml
- tests/tasks/tests_idempotency.yml
It has a very limited functionality, the proper HA functionality is available with the mssql_ha_configure variable
> fix: Remove outdated and confusing mssql_enable_ha variable

- tasks/main.yml
Enhancement:
Skip Prepare upgrade step if there is no current version
Reason:
Having `mssql_upgrade` enabled, while there is no current version installed failed with undefined variable `__mssql_current_version`. 
Result:
If no current version is installed, the prepare upgrade task is skipped and a fresh installation is done.
> fix: Only do an upgrade if there is a current version

- tasks/main.yml
- tests/tasks/cleanup.yml
- tests/tasks/tests_input_sql_file.yml
- tests/tests_configure_ha_cluster.yml
- tests/tests_include_vars_from_parent_2019.yml
Enhancement: Ignore `var-naming[no-role-prefix] ` ansible-lint checks inline
Reason: ansible-lint checks `var-naming[no-role-prefix] ` fail on some lines where the use of vars not starting with `mssql_` is required.
Result: The checks are ignored on affected lines.
> ci: Ignore `var-naming[no-role-prefix] ` ansible-lint checks inline

- README.md
- defaults/main.yml
- tasks/main.yml
- tasks/sqlcmd_input_file.yml
- tests/playbooks/tests_ad_integration.yml
- tests/tasks/verify_ad_auth.yml
- tests/templates/ad_create_login.j2
- vars/main.yml
Enhancement:
1. Add the `mssql_ad_join` variable to allow using other domain join methods.
2. Add the `mssql_ad_kerberos_user` and `mssql_ad_kerberos_password` variables to allow users to specify a user to obtain kerberos ticket for in the case that default user doesn't match.
Reason: Sometimes, users use other methods to manage joining to AD that would be broken if that role were to run.
Result:
1. Users can set `mssql_ad_join` to `false` and join managed nodes to AD themselves prior to running the role. By default, `mssql_ad_join` = `true`, so the current behavior is not changed.
2. Users can set `mssql_ad_kerberos_user` and `mssql_ad_kerberos_password` to obtain a kerberos ticket for a specific use if the user that the role selects by default doesn't work for them.
Issue Tracker …
> feat: Add mssql_ad_join and mssql_ad_kerberos_user to allow using other domain join methods

- README.md
- defaults/main.yml
- tasks/input_sql_files.yml
- tasks/main.yml
- tasks/sqlcmd_input_content.yml
- tests/tasks/tests_input_sql_file.yml
Enhancement: Add the ability to add SQL scripts as a content directly.
Reason: Previously, users could save SQL script to a file and input it with `mssql_pre_input_sql_file` and `mssql_post_input_sql_file`. Sometimes for shorter scripts it may be an overkill to create a separate file, and it would be easier to provide the script content to the role directly.
Result: With this update, users can provide a T-SQL script directly with `mssql_pre_input_sql_content` and `mssql_post_input_sql_content` variables.
> feat: Add the ability to input T-SQL scripts content in addition to files

- README.md
Enhancement:
- Remove redundant title lvl indentation
- Add syntax highlighting to all code blocks
- Fix indentation in lists
Reason: Improve README readability and fix syntax
> docs:  Improve README titles indentation and fix syntax

- tests/playbooks/tests_ad_integration.yml
Enhancement: Fix hardcoded domain name, it is randomized in IDM CI
Reason: ad_integration_realm is randomized in IDM CI hence need to use variables.
Cannot use variable for Administrator because test with `mssql_ad_join: false` does `ad_integration_user: null`
Result: Tests in IDM CI pass when run using trigger-test-suite-tool
> ci: fix hardcoded domain name, it is randomized in IDM CI

- tasks/main.yml
Enhancement: Remove `no_log: true` where it is not required.
Reason: `no_log: true` was set on `package_facts` and `service_facts` modules to have cleaner logs because the large output of this task is not helpful for logs. However, users might have issues with Ansible not able to run these modules e.g. because it is not able to find python interpreter, such issues were hard to troubleshoot with a hidden output.
Result: Tasks that use `package_facts` and `service_facts` modules do not use `no_log: true`, hence they print output when running `ansible-playbook` with `-v`.
Issue Tracker Tickets (Jira or BZ if any):
Fixes #240
> fix: Remove no_log: true where it is not required

- vars/RedHat.yml
Enhancement: Use GA repository for RHEL 9
Reason: Microsoft created a GA repository for RHEL 9 instead of the tech preview repository
Result: On RHEL 9, mssql-server is taken from the GA repository instead of the preview repository.
> chore: Use GA repository for RHEL 9

- README.md
- defaults/main.yml
- tasks/main.yml
- tests/tests_configure_ha_cluster_external.yml
- tests/tests_configure_ha_cluster_read_scale.yml
Enhancement: Add the `mssql_ha_prep_for_pacemaker` variable to configure SQL Server for Pacemaker.
Reason: Previously, the role did not have a variable to control whether to configure SQL Server for Pacemaker. Some users require to not configure for Pacemaker to use some custom HA solution.
Result: You can use the `mssql_ha_prep_for_pacemaker` variable to configure SQL Server for Pacemaker.
> feat: Add mssql_ha_prep_for_pacemaker for configuring HA solution other than Pacemaker

- .ostree/README.md
- .ostree/get_ostree_data.sh
- README-ostree.md
Use the `#!/usr/bin/env bash` shebang which is ansible-test friendly.
This means we can remove get_ostree_data.sh from the .sanity* files.
This also means we can remove the .sanity* files if we do not need
them otherwise.
Rename `pth` to `path` in honor of nscott
> refactor: get_ostree_data.sh use env shebang - remove from .sanity*

- README.md
- defaults/main.yml
- tasks/main.yml
- tests/tests_configure_ha_cluster_external.yml
Enhancement: Deprecate mssql_ha_cluster_run_role for mssql_manage_ha_cluster.
Reason: System roles consistently use variables in the form `mssql_manage_<rolename>` for managing components with other system roles. This role already uses `mssql_manage_firewall` and `mssql_manage_selinux`. Renaming `mssql_ha_cluster_run_role` to `mssql_manage_ha_cluster` brings consistency to variables names.
Result: When you set the deprecated `mssql_ha_cluster_run_role` variable, the role prints a message that this variable is deprecated and continues.
> chore: Deprecate mssql_ha_cluster_run_role for mssql_manage_ha_cluster

- .ansible-lint
- .github/workflows/ansible-lint.yml
- .github/workflows/ansible-managed-var-comment.yml
- .github/workflows/ansible-plugin-scan.yml
- .github/workflows/ansible-test.yml
The old ansible-community ansible-lint is deprecated.  There is a
new ansible-lint github action.
The latest Ansible repo gating tests run ansible-lint against
the collection format instead of against individual roles.
We have to convert the role to collection format before running
ansible-test.
This also requires tox-lsr 3.2.1 - bump other actions to use 3.2.1
Role developers can run this locally using
`tox -e collection,ansible-lint-collection`
See https://github.com/linux-system-roles/tox-lsr/pull/125
> ci: Use supported ansible-lint action; run ansible-lint against the collection

- README.md
- defaults/main.yml
- tasks/configure_storage_paths.yml
- tasks/main.yml
- tests/tasks/cleanup.yml
- tests/tasks/tests_idempotency.yml
- tests/tests_configure_ha_cluster_external.yml
Enhancement:
1. Ensure SELinux type for used ports
2. Set default mode for data and log storage directories 
Reason:
1. Custom TCP ports must have `mssql_port_t` SELinux type
3. `mssql_datadir_mode` and `mssql_logdir_mode` should have a default value for security
Result:
1. When mssql_manage_selinux is set to `true`, the role configures used ports with the `mssql_port_t` SELinux type
2. `mssql_datadir_mode` and `mssql_logdir_mode` variables have a default value of `'755'`
> fix:  Ensure selinux type for used ports, set default data and log dirmode

- tasks/main.yml
- tasks/sqlcmd_input_file.yml
- tests/tests_configure_ha_cluster_external.yml
- tests/tests_selinux_enforcing_2022.yml
Enhancement: Make the role wait for ha_cluster to finish configuration
Reason: The role does some actions after the `ha_cluster` role finishes, it needs to wait for the `pcs` to finish configuration.
Result: Run the  `crm_resource --wait` command after ha_cluster role finishes.
> fix: Make the role wait for ha_cluster to finish configuration

- README.md
- tasks/configure_storage_paths.yml
- tasks/main.yml
- tests/tasks/verify_settings.yml
- tests/tests_configure_ha_cluster_external.yml
- tests/tests_configure_ha_cluster_read_scale.yml
- tests/tests_selinux_enforcing_2022.yml
Enhancement: Add support for running SQL Server as a SELinux unconfined application with SELinux in enforcing mode on RHEL 9
Reason: This support was added by Microsoft
Result: Now you can run SQL Server as an unconfined application on RHEL 9 in the default enforcing SELinux mode
> fix: Running selinux unconfined is supported with permissive mode

- tests/tests_configure_ha_cluster_external.yml
Enhancement: Fix tests_configure_ha_cluster_external.yml
Reason:  Due to a bug RHEL 9 executed `pcs resource move move-with-constraint` instead of `pcs resource move-with-constraint`
Result:  Test executes `pcs resource move-with-constraint` on RHEL 9
> test: fix pcs resource move/move-with-constraint logic

- .collection/README.md
- meta/main.yml
- tasks/main.yml
- tasks/verify_password.yml
- vars/RedHat.yml
- vars/Suse.yml
Enhancement:
Support deployment of MSSQL Server on OpenSUSE and SLES
Reason:
Suse systems are officially supported by the MSSQL RPM packages and this role only needs a few changes to also support them.
Result:
The role can be used to install and configure MSSQL  on OpenSUSE and SLES systems.
Issue Tracker Tickets (Jira or BZ if any):
> feat: support OpenSUSE/SLES

- .github/workflows/ansible-lint.yml
- .github/workflows/ansible-managed-var-comment.yml
- .github/workflows/ansible-plugin-scan.yml
- .github/workflows/ansible-test.yml
- .yamllint.yml
- tasks/main.yml
- tests/tests_configure_ha_cluster_external.yml
The latest version of virtualenv does not support creating
python 2.7 virtualenvs.  Change our CI tests to restrict the version
of virtualenv<20.22.0 and tox<4.15 for py27 environments
Move pylint, flake8, and black checks to the py310 environment
which is currently supported by ansible-core 2.17 and its related
checkers such as ansible-lint and ansible-test
pylint now uses ansible-core 2.17 and restricts the version of
pylint to 3.1.0 which is the version used by ansible-test 2.17
Remove `extends: default` for .yamllint.yml.  The latest version
of ansible-lint will automatically incorporate local yamllint
settings unless there is an `extends:`.
The above changes require some fixes to the role code.
For more information, see
https://github.com/linux-system-roles/tox-lsr/pull/168
and …
> ci: tox-lsr 3.4.0 - fix py27 tests; move other checks to py310

- .github/workflows/tft.yml
This change is for running tests in Testing Farm CI. This is a replacement for
BaseOS CI that we are currently using. Running it Testing Farm gives us more
control.
It adds a workflow for running tests, and a plans directory containing a test
plan and a README-plans.md with some info.
Note that this workflow runs from the main branch. This means that changes to
the workflow must be merged to main, then pull requests will be able to run it.
This is because the workflow uses on: issue_comment context, this is a security
measure recommended by GitHub. It saves us from leaking organization secrets.
The functionality is WIP, so await future fixes and updates.
> ci: Improve tft plan and workflow

- tasks/main.yml
Enhancement: Fail on RHEL or CentOS 10 because it's not supported
Reason: Microsoft SQL Server does not support RHEL or CentOS 10 managed hosts yet
> chore: Fail on RHEL or CentOS 10 because it's not supported

- tasks/main.yml
Enhancement: Discover primary based on inventory_hostname
Reason: Using ansible_hostname causes an issue where role cannot find the primary HA instance. Using inventory_hostname instead fixes this.
Result: The role finds primary HA instance successfully.
> fix: Discover primary based on inventory_hostname

- tests/tests_configure_ha_cluster_external.yml
- tests/tests_configure_ha_cluster_read_scale.yml
Enhancement: Improve HA tests
Result:
* Remove mssql_version from inventory, set it in the playbook
* Set mssql_manage_selinux and mssql_run_selinux_confined to true on EL9
* Load softdog module for stonith to have at least one watchdog
> test: Improve HA tests

- tests/tests_configure_ha_cluster_external.yml
- tests/tests_configure_ha_cluster_read_scale.yml
Enhancement: In HA tests, revert mssql_run_selinux_confined: true on EL 9
Reason: RHEL 9 with selinux-confined mode doesn't support HA scenario due to SELinux denies on mssql-server side
> tests:  In HA tests, revert mssql_run_selinux_confined: true on EL 9

- README.md
- tasks/main.yml
- tests/playbooks/tests_ad_integration_join_false.yml
- tests/playbooks/tests_ad_integration_w_keytab.yml
Enhancement: Use new adutil functionality to enable AES encryption
Reason: Since adutil version 1.1.83, adutil supports enabling Kerberos AES 128 and AES 256 bit encryption when creating and modifying the user.
Result: The role automates enabling Kerberos AES 128 and AES 256 bit encryption, so the manual post-configuration task  is not required.
> feat: Use new adutil functionality to enable AES encryption

- meta/main.yml
- tasks/main.yml
- tests/tasks/assert_fail_on_unsupported_ver.yml
- tests/tasks/cleanup.yml
- tests/tests_accept_eula.yml
- tests/tests_include_vars_from_parent.yml
Enhancement: Add support for Fedora
Reason: SQL Server from RHEL 9 RPMs might work on latest Fedora.
> feat: Add support for Fedora

- README.md
- defaults/main.yml
- tasks/main.yml
- tasks/verify_password.yml
- tests/tasks/assert_fail_on_unsupported_ver.yml
- tests/tasks/cleanup.yml
- tests/tasks/tests_password.yml
- tests/tasks/verify_ad_auth.yml
- tests/tests_tls_2017.yml
- tests/tests_tls_2019.yml
- tests/tests_tls_2022.yml
- vars/main.yml
Enhancement: Add `mssql_tools_versions` variable to allow installing different versions of `mssql-tools` package.
Add `mssql_tls_self_sign` variable for specifying whether self-signed certificates are used, applicable when users set `mssql_tls_enable: true`.
Reason: Microsoft added a new version of the `mssql-tools` package - `mssql-tools18`. This package adds some new functionality, which is not backward-compatible with the previous versions, hence Microsoft added a new package `mssql-tools18` instead of just bumping the version of `mssql-tools`.
With `mssql-tools18`, when self-signed TLS certificates are used, it is required to set `-C` flag with `sqlcmd` to trust certificates.
Result: You can set `mssql_tools_versions` to install version 17, 18, or both version in parallel. By default, …
> feat: Add mssql_tools_versions to allow installing different versions

- README.md
- defaults/main.yml
- tasks/main.yml
- tests/playbooks/tests_ad_integration.yml
- tests/playbooks/tests_ad_integration_join_false.yml
- tests/playbooks/tests_ad_integration_w_keytab.yml
- tests/tests_2019_upgrade.yml
- tests/tests_2022_upgrade.yml
- tests/tests_accept_eula.yml
- tests/tests_configure_ha_cluster_external.yml
- tests/tests_configure_ha_cluster_read_scale.yml
- tests/tests_idempotency_2017.yml
- tests/tests_idempotency_2019.yml
- tests/tests_idempotency_2022.yml
- tests/tests_include_vars_from_parent.yml
- tests/tests_input_sql_file_2017.yml
- tests/tests_input_sql_file_2019.yml
- tests/tests_input_sql_file_2022.yml
- tests/tests_password_2017.yml
- tests/tests_password_2019.yml
- tests/tests_password_2022.yml
- tests/tests_selinux_enforcing_2022.yml
- tests/tests_tcp_firewall_2017.yml
- tests/tests_tcp_firewall_2019.yml
- tests/tests_tcp_firewall_2022.yml
- tests/tests_tls_2017.yml
- tests/tests_tls_2019.yml
- tests/tests_tls_2022.yml
Enhancement: Deprecate this variable to use a variable without a version number instead. The role now can install versions 17 and 18.
Reason: After adding `mssql_tools_versions`, this role is able to install odbc driver for mssql_tools 17 and 18. This update changes the variable for specific version 17 to be general.
Result: When users use the deprecated variable `mssql_accept_microsoft_odbc_driver_17_for_sql_server_eula`, the role notifies them to use the new variable, but continues to execute.
> chore: Deprecate mssql_accept_microsoft_odbc_driver_17_for_sql_server_eula

- tasks/main.yml
`ansible_pkg_mgr` is `dnf5` on Fedora 42 and ELN (i.e. the future RHEL 11).
---
Similar to https://github.com/linux-system-roles/cockpit/pull/205 , thanks @spetrosi for finding this!
> fix: Prepare for dnf5

- .github/workflows/qemu-kvm-integration-tests.yml
- tasks/main.yml
- tests/tasks/cleanup.yml
- tests/tasks/mssql-sever-increase-start-limit.yml
This is not nearly sufficient yet, but some initial steps which I would like to test and land in isolation -- these shouldn't break the "booted system" case.
> fix: Make service check work in container environments; plus two other bootc preparation fixes

- .github/workflows/ansible-lint.yml
- .github/workflows/ansible-managed-var-comment.yml
- .github/workflows/ansible-test.yml
- .github/workflows/qemu-kvm-integration-tests.yml
- tests/tasks/cleanup.yml
- tests/tasks/verify_settings.yml
This will make the qemu/kvm tests be tested in either
ascending or descending ASCII order.  This should give
us better test coverage of clean up scenarios which may
fail depending on the order of the previous tests.
Rename the qemu/kvm tests so that the statuses are shorter
and more intuitive.
Improve qemu/kvm test failure error reporting.
> ci: bump tox-lsr to 3.8.0; rename qemu/kvm tests

- README.md
- defaults/main.yml
- tasks/main.yml
- templates/configure_ag.j2
- templates/replicate_db.j2
- tests/tasks/assert_fail_on_unsupported_ver.yml
- tests/tasks/cleanup.yml
- tests/tasks/cleanup_ag.yml
- tests/tasks/tests_ha_single.yml
- tests/tasks/verify_contained.yml
- tests/templates/ag_is_contained.j2
- tests/templates/ag_is_reuse_system_db.j2
- tests/templates/alter_ag.j2
- tests/templates/drop_ag.j2
- tests/templates/drop_dbs.j2
- tests/tests_configure_ha_cluster_external.yml
- tests/tests_configure_ha_cluster_read_scale.yml
- tests/tests_ha_single_2017.yml
- tests/tests_ha_single_2019.yml
- tests/tests_ha_single_2022.yml
Feature: add support to create Availability Group (AG) with contained database, and reuse system database
add two new var in playbook:
1、
mssql_ha_ag_is_contained
if true, the ag created will be contained
if false, the var mssql_ha_ag_reuse_system_db will be false
Default: false
Type: bool
2、
mssql_ha_ag_reuse_system_db
if true, the contained ag will be reuse system database
Default: false
Type: bool
Reason:  These are used to specify whether to CONTAINED and REUSE SYSTEM DATABASE when creating new availability group, it's feature in SQL Server 2022 - see the doc from microsoft:
https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/contained-availability-groups-overview?view=sql-server-ver16
Result: Users are able to create contained databases and reuse system …
> feat: Add ` mssql_ha_ag_is_contained` and `mssql_ha_ag_reuse_system_db`

- tasks/main.yml
- tasks/sqlcmd_input_content.yml
- tasks/sqlcmd_input_file.yml
Enhancement: Retry setting up SQL Server and calling sqlcmd
Reason: Sometimes SQL Server is unstable and requires several attempts to connect properly. Currently, this happens when trying to set up SQL Server on EL 9 with SELinux in enforcing state.
Result: Attempts success after a couple retries.
> fix: Retry set up and sqlcms until success instead of conditions

- .github/workflows/ansible-lint.yml
- .github/workflows/ansible-managed-var-comment.yml
- .github/workflows/ansible-test.yml
- .github/workflows/build_docs.yml
- .github/workflows/changelog_to_tag.yml
- .github/workflows/codespell.yml
- .github/workflows/markdownlint.yml
- .github/workflows/pr-title-lint.yml
- .github/workflows/qemu-kvm-integration-tests.yml
- .github/workflows/test_converting_readme.yml
- .github/workflows/tft.yml
- .github/workflows/tft_citest_bad.yml
- .github/workflows/weekly_ci.yml
- .github/workflows/woke.yml
- contributing.md
- plans/test_playbooks_parallel.fmf
* Pass in a YAML true value as `__bootc_validation: true` using
the --extra-vars option to ensure that `__bootc_validation` is
treated as a boolean and not a string value.
`-e "__bootc_validation: true"`
You can also use JSON format:
`-e '{"__bootc_validation": true}'`
but YAML is simpler in this case.
* Use tox-lsr version 3.11.1
* Ensure the citest bad comment works when the test was cancelled in
addition to the failure case.
* Update contributing.md documentation
* Update number of nodes to use in testing farm, if needed
* remove unnecessary ansible-lint skips
> ci: rollout several recent changes to CI testing
