linux-system-roles/mssql

- examples/simple.yml
- templates/foo.conf.j2
I want to get rid of unused dirs to not pull them into a collection
Example playbook is included in README.md
The role currently does not use templates
> Remove unused directories

- tasks/mssql_conf_setting.yml
- tests/tests_tls.yml
Also, add this check to the tls test
Resolves #25
> Fix failing when changing TCP port to the default 1433

- README.md
Resolves #28
Add example playbooks to demonstrate what variables to use in different
situations
Resolves #26
Call the role by microsoft.sql.server to comply with the collection
format
> Improve example playbooks to be more specific

- README.md
> Clarify that the role expects users to have tls cert and key

- tasks/main.yml
> Install openldap-compat on fedora to provide libldap-2.4.so.2

- README.md
- defaults/main.yml
- tasks/main.yml
- vars/main.yml
Issue #57 
rpm key is now a variable to allow users to set it to something within their environment.
> Set rpm key to variable

- tasks/main.yml
> Remove unnecessary quotes from yaml strings

- README.md
> Replace FQDN with short names when configuring availability group

- tasks/main.yml
- tests/tests_configure_ha_cluster.yml
Add listener when mssql_ha_configure is true
tests: create test dbs by running the role
> Fix adding listener and creating test dbs

- CHANGELOG.md
[1.2.3] - 2022-08-25
- none
- Fix adding listener and creating test dbs (#107)
- Add listener when mssql_ha_configure is true
- tests: create test dbs by running the role
- none
> Version 1.2.3 - CHANGELOG.md [citest skip]

- README.md
- defaults/main.yml
- tasks/main.yml
- tests/tests_tls_2019.yml
- Introduce a variable mssql_certificates to set the certificate_requests.
- Add the test case to test_tls_2019.yml
> Use the certificate role to create the cert and the key

- README.md
- tasks/main.yml
- tests/tests_input_sql_file_2019.yml
> Allow *_input_sql_files vars to take lists and strings

- .github/workflows/weekly_ci.yml
Example of PR: https://github.com/ukulekek/testrepo/pull/7  
Also, change `'` to `"` for consistency and delete unneeded line
> weekly-ci: create a [citest] comment

- README.md
- defaults/main.yml
- tasks/main.yml
- tests/playbooks/tests_ad_integration.yml
> Make AD integration functionality more flexible

- CHANGELOG.md
Create changelog update and release for version 2.0.0
> docs(changelog): version 2.0.0 [citest skip]

- CHANGELOG.md
Create changelog update and release for version 2.0.1
> docs(changelog): version 2.0.1 [citest skip]

- .collection/README.md
Update information in a collection README
> docs: Update .collection/README.md

- .README.html
- CHANGELOG.md
Update changelog and .README.html for version 2.0.3
> docs(changelog): version 2.0.3 [citest skip]

- .README.html
- CHANGELOG.md
Update changelog and .README.html for version 2.1.0
> docs(changelog): version 2.1.0 [citest skip]

- .README.html
- CHANGELOG.md
Update changelog and .README.html for version 2.2.0
> docs(changelog): version 2.2.0 [citest skip]

- .README.html
- CHANGELOG.md
Update changelog and .README.html for version 2.2.1
> docs(changelog): version 2.2.1 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 2.2.2
> docs(changelog): version 2.2.2 [citest skip]

- .collection/README.md
Enhancement: Add RHEL 9 to supported versions in collection readme
> chore: Add RHEL 9 to supported versions in collection readme

- .README.html
- CHANGELOG.md
Update changelog and .README.html for version 2.2.3
> docs(changelog): version 2.2.3 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 2.3.0
> docs(changelog): version 2.3.0 [citest skip]

- .github/workflows/tft.yml
> ci: Fix condition for running TF tests

- .github/workflows/tft.yml
> ci: Fix condition for running TF tests 2

- .github/workflows/tft.yml
> ci: yq is pre-installed in ubuntu

- .github/workflows/tft.yml
- meta/main.yml
- plans/general.fmf
> ci: Add additional steps to enable EPEL on EL 7

- .github/workflows/tft.yml
- meta/main.yml
> ci: Get memory in a separate step

- .github/workflows/tft.yml
> ci: Allow simualteneous workflow runs in different PRs

- tests/tests_configure_ha_cluster_external.yml
- tests/tests_configure_ha_cluster_read_scale.yml
Enhancement:
* Remove extrainvocation of read-scale test
* Add example inventories
* Run configure_ha_cluster_reaad_scale test only when invntory has 3 nodes and zero witness nodes
> tests: Fix HA tests

- .README.html
- CHANGELOG.md
Update changelog and .README.html for version 2.3.1
> docs(changelog): version 2.3.1 [citest skip]

- .collection/README.md
Enhancement :Update collection readme to comply with the template
Reason:
https://access.redhat.com/articles/7068606 introduces a Certified Collections README Template that we want to comply with I kept content that was in the readme before, and add some to fill in suggested sections.
I left out the ## Testing section, it does not provide any helpful info for users imo, we describe how we test in our GitHub page https://linux-system-roles.github.io/.
> docs: Update collection readme to comply with the template

- .README.html
- CHANGELOG.md
Update changelog and .README.html for version 2.4.0
> docs(changelog): version 2.4.0 [citest skip]

- .README.html
- CHANGELOG.md
Update changelog and .README.html for version 2.5.0
> docs(changelog): version 2.5.0 [citest skip]

- .packit.yaml
Use Packit default behavior when updating version in spec and generating changelog entry
> ci: Update .packit.yaml

- .README.html
- CHANGELOG.md
Update changelog and .README.html for version 2.5.2
> docs(changelog): version 2.5.2 [citest skip]

- .github/workflows/changelog_to_tag.yml
- meta/main.yml
> ci: Modify changelog_to_tag workflow to work with .github automation

- vars/Suse.yml
Added missing mssql-tools18 support to suse
> fix: Support mssql-tools18 on suse
